characters:
  "1":
    name: "Patient 1"
    persona: "69歲男性，口腔癌術後第15天，整形外科病房"
    backstory: "右下齒齦鱗狀細胞癌，pT2N0M0, stage II。術後15天，右臉頰縫線處持續有黃色分泌物，傷口紅腫，預計兩天後全身麻醉清創手術。醫師查房說明病情和手術計畫。"
    goal: "向醫護人員清楚表達傷口狀況和對手術計畫的理解。"

  "2":
    name: "Patient 2" 
    persona: "59歲男性，口腔癌術後第20天，整形外科病房"
    backstory: "左頰黏膜鱗狀細胞癌，pT4bN0M0, pstage IVb。術後20天，痰液多且黏稠，無法自咳，咳嗽頻繁面部脹紅。已用加溫潮濕器、蒸氣治療但效果不佳，主訴吸不到氣。"
    goal: "尋求護理師協助改善呼吸困難，學習咳嗽技巧和呼吸方式。"

  "3":
    name: "Patient 3"
    persona: "57歲男性，口腔癌術後第25天，口腔外科病房"
    backstory: "左頰黏膜鱗狀細胞癌，pT4bN0M0, pstage IVb。術後25天，多日未下床，3天前可坐床緣，2天前站立，1天前病室內步行。今日目標病室走廊步行。醫師查房鼓勵活動。"
    goal: "積極參與復健活動，達成病室走廊步行的目標。"

  "4":
    name: "Patient 4"
    persona: "55歲男性，舌癌術後2個月，放療中"
    backstory: "舌鱗狀細胞癌，pT4bN0M0, pstage IV。放療第20次，雙側頰黏膜、舌頭、嘴唇口腔黏膜炎，疼痛、進食困難、食慾不佳。尋求護理和營養協助。"
    goal: "尋求緩解放療副作用的方法，改善口腔黏膜炎症狀和進食問題。"

  "5":
    name: "Patient 5"
    persona: "52歲女性，口腔癌術後2個月，放療中"
    backstory: "左頰黏膜鱗狀細胞癌，pT1N0M0, pstage I。放療第17次，因放療導致張口困難。物理治療師協助口腔復健。"
    goal: "積極參與口腔復健治療，改善張口困難。"

  "6":
    name: "Patient 6"
    persona: "48歲男性，口腔癌術後當天，整形外科病房"
    backstory: "右頰黏膜鱗狀細胞癌，pT4bN3bM0, stage IV。2024年6月腫瘤切除合併皮瓣重建術，2025年1月皮瓣修補術。術後右頸手術部位疼痛，恢復室已打Morphine，現疼痛5分。"
    goal: "尋求護理師協助緩解術後疼痛，調整臥位和使用止痛藥。"

  "7":
    name: "Patient 7"
    persona: "62歲男性，口腔癌術後一年，疑腫瘤復發入院檢查"
    backstory: "右頰鱗狀細胞癌，pT3N0M0, stage III。一年前手術、皮瓣重建、化療。近日右頸腫塊，疑復發入院詳檢。預計MRI、心超、肺功能、抽血、正子攝影。醫師解釋檢查事宜。"
    goal: "了解入院檢查的目的和流程，配合醫師完成檢查。"

  "8":
    name: "Patient 8"
    persona: "70歲女性，口腔癌術後第22天，整形外科轉口腔外科病房"
    backstory: "舌鱗狀細胞癌，pT4bN0M0, stage IV。術後22天傷口穩定，預計轉回口腔外科續照護。醫師說明後續治療計畫，安排4天後回整形外科慢性傷口中心追蹤。"
    goal: "了解轉回口腔外科病房的安排和後續傷口追蹤計畫。"

  "9":
    name: "Patient 9"
    persona: "70歲男性，口腔癌術後第10天，整形外科病房"
    backstory: "左後顎鱗狀細胞癌，pT4bN3bM0, stage IVb。術後10天傷口穩定，醫師說明後續計畫：引流管兩日<20ml移除，下床活動後移除導尿管，飲食達標移除中心靜脈導管，轉口外病房前換可發聲氣切管。"
    goal: "理解後續管路移除的標準和時間點，配合醫囑進行復原。"

  "10":
    name: "Patient 10"
    persona: "65歲女性，口腔癌術後第8天，整形外科病房"
    backstory: "左下齒齦及左側舌緣鱗狀細胞癌，pT4bN0M0, stage IVb。術後8天首次發燒，疑呼吸道感染。需痰液細菌培養。護理師指導照顧者拍痰技巧、病人咳痰技巧、擴胸運動。"
    goal: "配合呼吸道感染的檢查和治療，學習有效咳痰技巧。"

  "11":
    name: "Patient 11"
    persona: "52歲男性，舌癌術後，出院前指導管灌飲食"
    backstory: "左側舌緣鱗狀細胞癌，pT4bN0M0, stage IVb。術後預計出院，灌食管路需持續使用。護理師指導照顧者及病人鼻胃管/胃造口灌食。"
    goal: "學會鼻胃管或胃造口灌食的技巧，以便出院後居家照護。"

  "12":
    name: "Patient 12"
    persona: "61歲男性，舌癌術後，門診追蹤"
    backstory: "左側舌緣鱗狀細胞癌，pT4bN0M0, stage IVb。已完成手術、重建、化放療，規則門診追蹤。現為門診看診。"
    goal: "參與門診追蹤，了解病情恢復狀況和後續追蹤計畫。"