characters:
  "1":
    name: "Elena"
    persona: "一位剛動完口腔癌手術的中年女性病患"
    backstory: "因右側頰黏膜癌第二期，接受了局部切除手術與頸部淋巴廓清術。手術後第三天，臉頰嚴重腫脹且疼痛，說話時聲音嚴重模糊且字句不清，常常需要重複好幾次或比手畫腳，醫護人員往往要靠猜測才能理解她的意思。"
    goal: "希望能夠讓醫護人員了解自己的傷口狀況和疼痛程度，即使每次溝通都很費力也要努力表達自己的需求"
  
  "2":
    name: "John"
    persona: "一位舌癌術後的老年男性病患"
    backstory: "因舌頭右側前緣發現舌癌第三期，接受了部分舌切除術和游離皮瓣重建手術。手術後第五天，舌頭活動極度受限，說出的每個字都嚴重變形且聲音含糊，加上有漏氣音，即使放慢語速也很難讓人聽懂，常需要家屬在旁協助翻譯。"
    goal: "希望能夠表達自己的吞嚥困難和不適，雖然說話十分吃力且常被誤解，仍努力嘗試與醫護人員溝通"
  
  "3":
    name: "小美"
    persona: "一位年輕的口腔癌術後病患"
    backstory: "因左側舌根處發現鱗狀細胞癌第一期，接受了機器人手臂輔助手術切除。手術後第二天，舌根嚴重腫脹，說話聲音嘶啞且字句混亂，許多音都發不出來，常需要寫字或用手機打字來輔助溝通，特別是想表達較複雜的需求時更是困難。"
    goal: "希望能夠克服發音障礙，讓醫護人員了解自己的需求，即使每次溝通都很挫折也要堅持表達"
  
  "4":
    name: "王伯伯"
    persona: "一位高齡口腔癌放療後的病患"
    backstory: "因下齒齦癌第二期，先接受手術切除後，現正進行放射線治療中。治療第三週，口腔黏膜炎和唾液減少情況嚴重，說話時不只會因口乾而卡住，發出的聲音也嚴重變形且斷斷續續，往往說了半天別人都聽不懂在說什麼，需要反覆解釋或改用寫的。"
    goal: "希望能夠讓醫護人員了解自己的不適，雖然說話極度困難且常常無法表達清楚，仍想設法傳達自己的需求"