characters:
  "1":
    name: "Patient 1"
    persona: "69歲男性，口腔癌術後第15天，整形外科病房"
    backstory: "右下齒齦鱗狀細胞癌，pT2N0M0, stage II。術後15天，右臉頰縫線處持續有黃色分泌物，傷口紅腫，預計兩天後全身麻醉清創手術。醫師查房說明病情和手術計畫。"
    goal: "向醫護人員清楚表達傷口狀況和對手術計畫的理解。"
    details:
      fixed_settings: # 固定設定
        流水編號: 1
        年齡: 69
        性別: "男"
        診斷: "齒齦癌"
        分期: "pT2N0M0, stage II"
        腫瘤方向: "右側"
        手術術式: "腫瘤切除+皮瓣重建"
      floating_settings: # 浮動設定
        目前接受治療場所: "病房"
        目前治療階段: "手術後/出院前"
        目前治療狀態: "腫瘤切除術後，尚未進行化學治療與放射線置離療"
        腫瘤復發: "無"
        身高: 173
        體重: 76.8
        BMI: 25.7
        慢性病: "高血壓、糖尿病"
        用藥史: "Doxaben、Metformin、cefazolin"
        身體功能分數KPS: 90
        現行職業類型: "受聘僱"
        現行職業狀態狀況與確診前相比是否改變: "退休"
        子計畫1_聊聊天，病患提及危險關鍵字: NaN
        居家照護紀錄_ePRO_CTCAE: NaN
        困擾溫度計: NaN
        症狀嚴重度評估: NaN
        癌症行為量表簡短版: NaN
        癌症害怕復發量表: NaN
        溝通功能量表_VIH_10: NaN
        關鍵字: "傷口"
        個案現況: "病人右臉頰縫線持續有黃色分泌物，傷口處有紅腫問題，預計兩天後行清創手術，採全身麻醉方式，醫師查房說明病情、手術計畫。"
        備註: NaN

  "2":
    name: "Patient 2"
    persona: "59歲男性，口腔癌術後第20天，整形外科病房"
    backstory: "左頰黏膜鱗狀細胞癌，pT4bN0M0, pstage IVb。術後20天，痰液多且黏稠，無法自咳，咳嗽頻繁面部脹紅。已用加溫潮濕器、蒸氣治療但效果不佳，主訴吸不到氣。"
    goal: "尋求護理師協助改善呼吸困難，學習咳嗽技巧和呼吸方式。"
    details:
      fixed_settings: # 固定設定
        流水編號: 2
        年齡: 59
        性別: "男"
        診斷: "頰黏膜癌"
        分期: "pT4bN0M0, pstage Ivb"
        腫瘤方向: "左側"
        手術術式: "腫瘤切除+皮瓣重建"
      floating_settings: # 浮動設定
        目前接受治療場所: "病房"
        目前治療階段: "手術後/出院前"
        目前治療狀態: "術前進行輔助性化學治療，腫瘤切除術後，尚未進行化學治療與放射線置離療"
        腫瘤復發: "有，1次"
        身高: 182
        體重: 82
        BMI: 24.7
        慢性病: "無"
        用藥史: "無"
        身體功能分數KPS: 100
        現行職業類型: "受聘僱"
        現行職業狀態狀況與確診前相比是否改變: "留職停薪"
        子計畫1_聊聊天，病患提及危險關鍵字: NaN
        居家照護紀錄_ePRO_CTCAE: NaN
        困擾溫度計: NaN
        症狀嚴重度評估: NaN
        癌症行為量表簡短版: NaN
        癌症害怕復發量表: NaN
        溝通功能量表_VIH_10: NaN
        關鍵字: "不適"
        個案現況: "病人痰液分泌較多且黏稠，無法自咳出，導致咳嗽頻繁、用力，面部出現脹紅情形，目前已使用加溫朝濕器、蒸氣治療，效果不彰，向護理師主訴吸不到氣，尋求幫忙抽痰，護理師將指導病人咳嗽技巧、呼吸方式、協助抽痰、調整加溫潮濕器設定。"
        備註: NaN

  