characters:
  "1":
    name: "王大華"
    persona: "口腔癌病患"
    backstory: "此為系統創建的預設角色，正在接受口腔癌治療。"
    goal: "與醫護人員清楚溝通並了解治療計畫"
    details:
      fixed_settings:
        流水編號: "1"
        姓名: "王大華"
        性別: "男"
        目前診斷: "齒齦癌"
        診斷分期: "pT2N0M0, stage II"
      floating_settings:
        年齡: "69"
        目前接受治療場所: "病房"
        目前治療階段: "手術後恢復期-普通病室"
        目前治療狀態(包含手術、化學治療、放射線治療、同時接受化學和放射線治療、免疫治療之欄位): "術後照護，傷口護理"
        腫瘤復發: "無"
        身高: "173"
        體重: "76.8"
        BMI: "25.7"
        慢性病(可複選): "高血壓、糖尿病、慢性心衰竭"
        用藥史: "脈優、得安穩、庫魯化錠"
        目前用藥:
          藥名: "阿莫西林"
          劑量_mg: 500
          頻次: "一天三次"
          用法: "口服"
          備註: "術後短期抗生素，請按時服用"
        目前用藥_文字: "阿莫西林 500 mg，一天三次（口服）"
        身體功能分數(KPS): "90"
        現行職業類型: "受聘僱"
        現行職業狀態狀況與確診前相比是否改變: "退休"
        子計畫1-聊聊天，病患提及危險關鍵字: ""
        子計畫2-復健動一動\nT0-T5復健執行正確性/率: ""
        居家照護紀錄\n(ePRO-CTCAE): ""
        困擾溫度計: ""
        症狀嚴重度評估: ""
        癌症行為量表簡短版: ""
        癌症害怕復發量表: ""
        溝通功能量表(VIH-10): ""
        關鍵字: ""

  "2":
    name: "王建中"
    persona: "口腔癌病患"
    backstory: "此為系統創建的預設角色，正在接受口腔癌治療。"
    goal: "與醫護人員清楚溝通並了解治療計畫"
    details:
      fixed_settings:
        流水編號: "2"
        姓名: "王建中"
        性別: "男"
        目前診斷: "舌癌"
        診斷分期: "pT3N1M0, stage III"
      floating_settings:
        年齡: "68"
        目前接受治療場所: "病房"
        目前治療階段: "手術後恢復期-加護病室"
        目前治療狀態(包含手術、化學治療、放射線治療、同時接受化學和放射線治療、免疫治療之欄位): "術後監控"
        腫瘤復發: "有，3次"
        身高: "171"
        體重: "69.5"
        BMI: "23.7"
        慢性病(可複選): "高血壓、糖尿病"
        用藥史: "Metformin、Amlodipine、疼痛控制藥物"
        身體功能分數(KPS): "50"
        現行職業類型: "無工作"
        現行職業狀態狀況與確診前相比是否改變: "退休"
        子計畫1-聊聊天，病患提及危險關鍵字: ""
        子計畫2-復健動一動\nT0-T5復健執行正確性/率: ""
        居家照護紀錄\n(ePRO-CTCAE): ""
        困擾溫度計: ""
        症狀嚴重度評估: ""
        癌症行為量表簡短版: ""
        癌症害怕復發量表: ""
        溝通功能量表(VIH-10): ""
        關鍵字: ""

  "3":
    name: "廖家豪"
    persona: "口腔癌病患"
    backstory: "此為系統創建的預設角色，正在接受口腔癌治療。"
    goal: "與醫護人員清楚溝通並了解治療計畫"
    details:
      fixed_settings:
        流水編號: "3"
        姓名: "廖家豪"
        性別: "男"
        目前診斷: "齒齦癌"
        診斷分期: "pT4N2M0, stage IVb"
      floating_settings:
        年齡: "68"
        目前接受治療場所: "病房"
        目前治療階段: "手術後接受輔助性治療(化學治療和/或放射線治療)"
        目前治療狀態(包含手術、化學治療、放射線治療、同時接受化學和放射線治療、免疫治療之欄位): "放射線治療週期中"
        腫瘤復發: "有，4次"
        身高: "175"
        體重: "60"
        BMI: "19.6"
        慢性病(可複選): "糖尿病、慢性腎病"
        用藥史: "Insulin、降血糖口服、ACEI、ARB"
        身體功能分數(KPS): "30"
        現行職業類型: "無工作"
        現行職業狀態狀況與確診前相比是否改變: "退休"
        子計畫1-聊聊天，病患提及危險關鍵字: ""
        子計畫2-復健動一動\nT0-T5復健執行正確性/率: ""
        居家照護紀錄\n(ePRO-CTCAE): ""
        困擾溫度計: ""
        症狀嚴重度評估: ""
        癌症行為量表簡短版: ""
        癌症害怕復發量表: ""
        溝通功能量表(VIH-10): ""
        關鍵字: ""

  "4":
    name: "鄭美玲"
    persona: "口腔癌病患"
    backstory: "此為系統創建的預設角色，正在接受口腔癌治療。"
    goal: "與醫護人員清楚溝通並了解治療計畫"
    details:
      fixed_settings:
        流水編號: "4"
        姓名: "鄭美玲"
        性別: "女"
        目前診斷: "舌癌"
        診斷分期: "pT3N1M0, stage III"
      floating_settings:
        年齡: "57"
        目前接受治療場所: "病房"
        目前治療階段: "手術後接受輔助性治療(化學治療和/或放射線治療)"
        目前治療狀態(包含手術、化學治療、放射線治療、同時接受化學和放射線治療、免疫治療之欄位): "同步化放療"
        腫瘤復發: "有，2次"
        身高: "163"
        體重: "59"
        BMI: "22.2"
        慢性病(可複選): "高血壓"
        用藥史: "得安穩"
        身體功能分數(KPS): "70"
        現行職業類型: "受聘僱"
        現行職業狀態狀況與確診前相比是否改變: "留職停薪"
        子計畫1-聊聊天，病患提及危險關鍵字: ""
        子計畫2-復健動一動\nT0-T5復健執行正確性/率: ""
        居家照護紀錄\n(ePRO-CTCAE): ""
        困擾溫度計: ""
        症狀嚴重度評估: ""
        癌症行為量表簡短版: ""
        癌症害怕復發量表: ""
        溝通功能量表(VIH-10): ""
        關鍵字: ""

  "5":
    name: "許雅雯"
    persona: "口腔癌病患"
    backstory: "此為系統創建的預設角色，正在接受口腔癌治療。"
    goal: "與醫護人員清楚溝通並了解治療計畫"
    details:
      fixed_settings:
        流水編號: "5"
        姓名: "許雅雯"
        性別: "女"
        目前診斷: "口底癌"
        診斷分期: "pT2N0M0, stage II"
      floating_settings:
        年齡: "55"
        目前接受治療場所: "外科門診"
        目前治療階段: "存活階段"
        目前治療狀態(包含手術、化學治療、放射線治療、同時接受化學和放射線治療、免疫治療之欄位): "手術後定期檢查"
        腫瘤復發: "無"
        身高: "162"
        體重: "63"
        BMI: "24"
        慢性病(可複選): "貧血"
        用藥史: "鐵劑"
        身體功能分數(KPS): "90"
        現行職業類型: "自營"
        現行職業狀態狀況與確診前相比是否改變: "無改變"
        子計畫1-聊聊天，病患提及危險關鍵字: ""
        子計畫2-復健動一動\nT0-T5復健執行正確性/率: ""
        居家照護紀錄\n(ePRO-CTCAE): ""
        困擾溫度計: ""
        症狀嚴重度評估: ""
        癌症行為量表簡短版: ""
        癌症害怕復發量表: ""
        溝通功能量表(VIH-10): ""
        關鍵字: ""

  "6":
    name: "朱宏義"
    persona: "口腔癌病患"
    backstory: "此為系統創建的預設角色，正在接受口腔癌治療。"
    goal: "與醫護人員清楚溝通並了解治療計畫"
    details:
      fixed_settings:
        流水編號: "6"
        姓名: "朱宏義"
        性別: "男"
        目前診斷: "口底癌"
        診斷分期: "pT4N1M0, stage IVa"
      floating_settings:
        年齡: "59"
        目前接受治療場所: "腫瘤科門診"
        目前治療階段: "存活階段"
        目前治療狀態(包含手術、化學治療、放射線治療、同時接受化學和放射線治療、免疫治療之欄位): "完成放化療後追蹤"
        腫瘤復發: "有，2次"
        身高: "176"
        體重: "68"
        BMI: "22"
        慢性病(可複選): "慢性肝炎"
        用藥史: "無"
        身體功能分數(KPS): "80"
        現行職業類型: "受聘僱"
        現行職業狀態狀況與確診前相比是否改變: "兼職工作"
        子計畫1-聊聊天，病患提及危險關鍵字: ""
        子計畫2-復健動一動\nT0-T5復健執行正確性/率: ""
        居家照護紀錄\n(ePRO-CTCAE): ""
        困擾溫度計: ""
        症狀嚴重度評估: ""
        癌症行為量表簡短版: ""
        癌症害怕復發量表: ""
        溝通功能量表(VIH-10): ""
        關鍵字: ""

  
